"""Sphinx configuration for the MedVision documentation site.

Authoring is done in Markdown via MyST-Parser; the API reference is generated by
autodoc/autosummary over the ``medvision_bm`` source tree. To keep Read the Docs
builds light and reliable, the heavy ML dependencies (and the vendored lmms-eval
fork) are mocked rather than installed — see ``autodoc_mock_imports`` below.
"""

import os
import sys

# Make the in-tree source importable for autodoc. Resolve relative to THIS file
# (not the build CWD) so the worktree's own src/ wins over any installed copy.
_SRC = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "src"))
sys.path.insert(0, _SRC)

# -- Project information ------------------------------------------------------
project = "MedVision"
author = "Yongcheng Yao and the MedVision contributors"
copyright = "2026, MedVision authors — code under CC-BY 4.0"

try:
    from medvision_bm import __version__ as _version

    version = _version
    release = _version
except Exception:  # pragma: no cover - version is best-effort
    version = release = "1.2.0"

# -- General configuration ----------------------------------------------------
extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
    "sphinx_design",
]

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# MyST (Markdown) extensions used across the docs.
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "linkify",
    "substitution",
    "attrs_inline",
    "fieldlist",
]
myst_heading_anchors = 3

# -- Autodoc / autosummary ----------------------------------------------------
autosummary_generate = True
autodoc_typehints = "description"
autoclass_content = "both"
autodoc_member_order = "bysource"
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "show-inheritance": True,
}

# Modules imported at module scope by the documented code but too heavy (or
# environment-specific) to install on the docs builder. The final entry mocks the
# vendored lmms-eval fork so that parse_outputs/summarize_{AD,TL}_task import
# cleanly without pulling the full evaluation harness.
autodoc_mock_imports = [
    "torch",
    "torchvision",
    "accelerate",
    "datasets",
    "transformers",
    "trl",
    "peft",
    "vllm",
    "scipy",
    "psutil",
    "PIL",
    "cv2",
    "tqdm",
    "matplotlib",
    "flash_attn",
    "wandb",
    "safetensors",
    "einops",
    "qwen_vl_utils",
    "huggingface_hub",
    "medvision_bm.medvision_lmms_eval",
]

# Napoleon (Google/NumPy-style docstrings backfilled in src/).
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_use_rtype = True

# -- HTML output --------------------------------------------------------------
html_theme = "sphinx_book_theme"
html_title = "MedVision"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_theme_options = {
    "logo": {
        "image_light": "_static/medvision-logo.svg",
        "image_dark": "_static/medvision-logo-dark.svg",
    },
    "repository_url": "https://github.com/YongchengYAO/MedVision",
    "repository_branch": "master",
    "use_repository_button": True,
    "use_issues_button": True,
    "home_page_in_toc": True,
    "show_navbar_depth": 1,
    "show_toc_level": 2,
}

# Copybutton: strip shell/REPL prompts when copying code blocks.
copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regex = True
